name: test-workflow
on:
  workflow_dispatch:
    inputs:
      pre-release-tag:
        description: 'The pre-release tag use in the version'
        required: false
        default: 'pre'
      dist-tag:
        description: 'The dist-tag use'
        required: false
        default: 'next'
      dependencies-to-update:
        description: 'csv of dependencies to update with the dist-tag'
        required: false
        default: 'semver,to-camel-case'
      package-name:
        description: 'override the package name'
        required: false
        default: 'my-cli-next'

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name test-user
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: |
          npm install
          npm test
      - name: Update your package.json with an npm pre-release version, and update dependencies with pre-release versions
        uses: adobe/update-prerelease-npm-version@v1.0.0
        id: pre-release-version
        with:
          pre-release-tag: ${{ github.event.inputs.pre-release-tag }}
          dependencies-to-update: ${{ github.event.inputs.dependencies-to-update }}
          dependencies-to-update-version-tag: ${{ github.event.inputs.dist-tag }}
          package-name: ${{ github.event.inputs.package-name }}

      - run: cat package.json
      - run: echo ${{ steps.pre-release-version.outputs.pre-release-version }} 
