name: test-workflow
on:
  workflow_dispatch:
    inputs:
      pre_release_tag:
        description: 'The pre-release tag to use'
        required: false
        default: 'pre'
jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name test-user
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: |
          npm install
          npm test
      - name: Update your package.json with an npm pre-release version
        id: pre_release_version
        uses: shazron/update-prerelease-npm-version@v1.0.0
        with:
          pre-release-tag: ${{ github.event.inputs.pre_release_tag }}
      - run: cat package.json
      - run: echo ${{ steps.pre_release_version.outputs.pre-release-version }} 
